<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Hash;
use Tests\TestCase;

class UserTest extends TestCase
{
    use RefreshDatabase;

    protected $token;

    protected $user;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = $this->createUser();
        $this->token = $this->createToken();
    }

    public function data($name = 'test', $email = 'test2@gmail.com')
    {
        return [
            'name' => $name,
            'email' => $email,
            'password' => Hash::make('123456'),
        ];
    }

    public function test_user_can_register()
    {
        $this->post(route('user.register'), $this->data())->assertStatus(200)->assertSee('success');
    }

    public function test_user_can_login()
    {
        $this->post(route('user.login'), ['email' => 'test@gmail.com', 'password' => '123456'])->assertStatus(200)->assertSee('token');
    }
}
